apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-java-springboot-basic-multi-components-dock
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-java-springboot-basic-multi-components-dock
    app.kubernetes.io/part-of: multi-components-dockerfile
  name: devfile-sample-java-springboot-basic-multi-components-dock
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: devfile-sample-java-springboot-basic-multi-components-dock
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: devfile-sample-java-springboot-basic-multi-components-dock
    spec:
      containers:
      - image: java-springboot-image:latest
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
