apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-src-docker-multi-components-dockerfile
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-src-docker-multi-components-dockerfile
    app.kubernetes.io/part-of: multi-components-dockerfile
  name: python-src-docker-multi-components-dockerfile
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: python-src-docker-multi-components-dockerfile
status:
  loadBalancer: {}
