apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-nodejs-basic-multi-components-dockerfile
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-nodejs-basic-multi-components-dockerfile
    app.kubernetes.io/part-of: multi-components-dockerfile
  name: devfile-sample-nodejs-basic-multi-components-dockerfile
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: devfile-sample-nodejs-basic-multi-components-dockerfile
status:
  loadBalancer: {}
