apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-src-none-multi-components-dockerfile
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-src-none-multi-components-dockerfile
    app.kubernetes.io/part-of: multi-components-dockerfile
  name: python-src-none-multi-components-dockerfile
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: python-app
    app.kubernetes.io/instance: python-src-none-multi-components-dockerfile
status:
  loadBalancer: {}
